// Bilingual atmosphere text blocks — structured as { de: {...}, en: {...} }
export const textBlocks = {
  de: {
    locations: [
      'im flackernden Nexus-Kontrollraum',
      'am Rand des pulsierenden Energie-Kerns',
      'in der kristallinen Verbindungsbrücke',
      'tief im Datenstrom-Archiv',
      'vor dem versiegelten Dimensionstor',
      'in der schwebenden Beobachtungsplattform',
      'zwischen den rotierenden Realitätsringen',
    ],
    moods: [
      'Eine schwere Stille liegt über dem Nexus.',
      'Die Energie-Spannung ist fast greifbar.',
      'Jeder Schritt durch die Realität wirkt zu laut.',
      'Etwas an diesem Ort der Macht fühlt sich falsch an.',
      'Niemand sagt etwas, doch alle spüren die Verschiebung.',
      'Die Luft riecht nach verbrannter Realität und altem Licht.',
      'Ein unbehagliches Gefühl kriecht durch alle Dimensionen.',
    ],
    events: [
      'Ein ferner Riss im Realitätsgefüge beginnt zu vibrieren.',
      'Die Nexus-Lichter flackern unruhig durch alle Farben.',
      'Hinter einer Dimensions-Wand hallt ein dumpfer Impuls.',
      'Ein Kontrollkristall springt knisternd an.',
      'Eine versiegelte Realitätskammer reagiert mit einem scharfen Klicken.',
      'Irgendwo tropft Energie-Kondensat auf blankes Metall.',
      'Ein kurzes Interdimensional-Zischen — dann Stille.',
    ],
    reactions: [
      'Die Gruppe bleibt abrupt stehen.',
      'Jemand flüstert eine Warnung durch den Nexus-Funk.',
      'Ein nervöser Blick geht durch die Runde.',
      'Für einen Moment wagt niemand zu atmen.',
      'Sofort richten sich alle Blicke auf den Ursprung des Impulses.',
      'Lyra hebt die Hand — Zeichen für sofortigen Stopp.',
      'Kairo greift instinktiv nach seinem Nexus-Gerät.',
    ],
    consequences: [
      'Von jetzt an kann jede Entscheidung alle Realitäten verändern.',
      'Die nächsten Momente werden über den Kurs des Nexus entscheiden.',
      'Es gibt keinen einfachen Rückweg durch die Dimensionen mehr.',
      'Ab jetzt zählt jede falsche Bewegung doppelt.',
      'Der weitere Verlauf hängt vollständig von eurem Mut ab.',
      'Was auch immer jetzt kommt — ihr habt es selbst gewählt.',
      'Das Nexus hat registriert, dass ihr hier seid.',
    ],
  },
  en: {
    locations: [
      'in the flickering Nexus control room',
      'at the edge of the pulsing energy core',
      'on the crystalline connection bridge',
      'deep within the data stream archive',
      'before the sealed dimensional gate',
      'on the floating observation platform',
      'between the rotating reality rings',
    ],
    moods: [
      'A heavy silence lies over the Nexus.',
      'The energy tension is almost tangible.',
      'Every step through reality feels too loud.',
      'Something about this place of power feels wrong.',
      'No one speaks, yet everyone senses the shift.',
      'The air smells of burned reality and ancient light.',
      'An unsettling feeling crawls through all dimensions.',
    ],
    events: [
      'A distant rift in the fabric of reality begins to vibrate.',
      'The Nexus lights flicker restlessly through all colors.',
      'Behind a dimensional wall, a dull pulse echoes.',
      'A control crystal crackles to life.',
      'A sealed reality chamber responds with a sharp click.',
      'Somewhere, energy condensate drips onto bare metal.',
      'A brief interdimensional hiss — then silence.',
    ],
    reactions: [
      'The group stops abruptly.',
      'Someone whispers a warning over the Nexus comm.',
      'A nervous glance passes through the group.',
      'For a moment, no one dares to breathe.',
      'All eyes immediately turn to the source of the pulse.',
      'Lyra raises her hand — a signal to halt immediately.',
      'Kairo instinctively reaches for his Nexus device.',
    ],
    consequences: [
      'From now on, every decision can change all realities.',
      'The next moments will determine the course of the Nexus.',
      'There is no easy way back through the dimensions.',
      'From now on, every wrong move counts double.',
      'What happens next depends entirely on your courage.',
      'Whatever comes now — you chose it yourself.',
      'The Nexus has registered that you are here.',
    ],
  },
};
