export const textBlocks = {
  locations: [
    'im flackernden Kontrollraum',
    'im kalten Archivgang',
    'im engen Wartungstunnel',
    'unter dem offenen Dach der Anlage',
    'vor der versiegelten Labortür',
    'in der verlassenen Schleusenkammer',
    'zwischen den erloschenen Reaktorringen',
  ],
  moods: [
    'Eine schwere Stille liegt in der Luft.',
    'Die Spannung ist fast greifbar.',
    'Jeder Schritt wirkt plötzlich zu laut.',
    'Etwas an diesem Ort fühlt sich falsch an.',
    'Niemand sagt etwas, doch alle spüren die Gefahr.',
    'Die Luft riecht nach verbranntem Metall und altem Staub.',
    'Ein unbehagliches Gefühl kriecht die Wirbelsäule hinauf.',
  ],
  events: [
    'Ein ferner Alarm beginnt aufzuheulen.',
    'Die Lichter flackern unruhig über euch.',
    'Hinter einer Metallwand hallt ein dumpfer Schlag.',
    'Ein Kontrollmonitor springt knisternd an.',
    'Eine verriegelte Tür reagiert plötzlich mit einem scharfen Klicken.',
    'Irgendwo tropft Wasser auf blankes Eisen.',
    'Ein kurzes Zischen — dann Stille.',
  ],
  reactions: [
    'Die Gruppe bleibt abrupt stehen.',
    'Jemand flüstert eine Warnung.',
    'Ein nervöser Blick geht durch die Runde.',
    'Für einen Moment wagt niemand zu atmen.',
    'Sofort richten sich alle Blicke auf den Ursprung des Geräuschs.',
    'Mara hebt die Hand — Zeichen für sofortigen Stopp.',
    'Iven greift instinktiv nach seinem Werkzeug.',
  ],
  consequences: [
    'Von jetzt an kann jede Entscheidung alles verändern.',
    'Die nächsten Minuten werden über euren Kurs entscheiden.',
    'Es gibt keinen einfachen Rückweg mehr.',
    'Ab jetzt zählt jede falsche Bewegung doppelt.',
    'Der weitere Verlauf hängt nun vollständig von eurem Mut ab.',
    'Was auch immer jetzt kommt — ihr habt es selbst gewählt.',
    'Die Anlage hat registriert, dass ihr hier seid.',
  ],
};
